# Generated by Django 6.1 on 2026-08-11 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_avatar_userconfirmation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userconfirmation',
            options={'ordering': ('-expiration_time',), 'verbose_name': 'user confirmation ', 'verbose_name_plural': 'user confirmations'},
        ),
        migrations.AlterModelTable(
            name='userconfirmation',
            table='user_confirmations',
        ),
    ]
