# Generated by Django 6.1 on 2026-08-11 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_userconfirmation_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('-date_joined',), 'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AlterModelOptions(
            name='userconfirmation',
            options={'ordering': ('-expiration_time',), 'verbose_name': 'user confirmation', 'verbose_name_plural': 'user confirmations'},
        ),
    ]
