# Generated by Django 6.1 on 2026-08-15 09:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='caption',
            field=models.TextField(blank=True, null=True, validators=[django.core.validators.MaxLengthValidator(2000)]),
        ),
    ]
