# Generated by Django 6.1 on 2026-08-17 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('follow', 'follow'), ('un_follow', 'un_follow'), ('like', 'like'), ('comment', 'comment_like'), ('comment_like', 'comment_like')], max_length=12),
        ),
    ]
