# Generated by Django 6.1 on 2026-08-18 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0003_alter_notification_comment_alter_notification_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('follow', 'follow'), ('un_follow', 'un_follow'), ('post_like', 'post_like'), ('comment', 'comment'), ('comment_like', 'comment_like')], max_length=12),
        ),
    ]
