# Generated by Django 6.1 on 2026-08-18 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0004_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('follow', 'follow'), ('un_follow', 'un_follow'), ('post_like', 'post_like'), ('post_unlike', 'post_unlike'), ('comment', 'comment'), ('comment_like', 'comment_like'), ('comment_unlike', 'comment_unlike')], max_length=14),
        ),
    ]
